version: "3"

services:
  db:
    image: postgres
    container_name: postgres-fortbrasil
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  api:
    image: api-fortbrasil
    container_name: api-fortbrasil
    build: .
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    restart: always
    stdin_open: true
    tty: true
